### ISSUE TITLE
Remove disqus and use internal comment tool

### ISSUE THREAD

**Issue by filipeximenes** [fixmydjango/fixmydjango#34]
The new internal comment tool must have
- Markdown support
- Identify user

**Comment by renatooliveira** [comment]
Spliting this task in smaller ones

**Comment by alessandroHenrique** [comment]
Hey @filipeximenes @andersonresende We're already using django_markdown to edit the **How to reproduce** field in the Error form. 

But django_markdown does not support django >= 1.8 Because it tries to do the following: 
`from django.conf.urls import patterns, url` 
Causing the error: `ImportError: cannot import name 'patterns'.`

Eve though you forked the django_markedown to fix that, sometimes the django_markdown is not working when you submit a new Error.

We could try use the [django-pagedown](https://github.com/timmyomahony/django-pagedown), it's straightforward to use, we can make a preview and customize the css of the editor.

**Comment by andersonresende** [comment]
@alessandroHenrique I think this lib only works inside the django admin. Could you check?

**Comment by alessandroHenrique** [comment]
@andersonresende I just checked the django-pagedown lib in the error form, placing it in the `How to reproduce` field and it worked.

**Comment by andersonresende** [comment]
@alessandroHenrique cool!
